import React, { useState, useEffect } from 'react';
import { Table, TableRow, TableCell, TableBody, List, ListItem, ListItemText } from '@material-ui/core';

const AuthorStory = (props) => {
  return(
    <>
      <List>
        <ListItem>
          <ListItemText
            className={props.classes.title}
            primary="
            合格体験記
            "
          />
        </ListItem>
      </List>
      <Table>
        <TableBody>
          <TableRow>
            <TableCell>
              <b>
              今回は何回目の受験か
              </b>
            </TableCell>
            <TableCell>
              {props.story.times}
            </TableCell>
          </TableRow>
          {props.story.studyHoursBefore &&
            <TableRow>
              <TableCell>
                <b>
                前回の受験までに勉強した時間を教えて下さい。
                </b>
              </TableCell>
              <TableCell>
                {props.story.studyHoursBefore}
              </TableCell>
            </TableRow>
          }
          <TableRow>
            <TableCell>
              <b>
              勉強を開始した時期
              </b>
            </TableCell>
            <TableCell>
              {props.story.start}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              受験までに勉強した時間
              </b>
            </TableCell>
            <TableCell>
              {props.story.hours}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              平日の平均勉強時間
              </b>
            </TableCell>
            <TableCell>
              {props.story.aveHoursDays}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              休日（土・日・祝）の平均勉強時間
              </b>
            </TableCell>
            <TableCell>
              {props.story.aveHoursHols}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              勉強方法
              </b>
            </TableCell>
            <TableCell>
              {props.story.studyType}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              利用した教材
              </b>
            </TableCell>
            <TableCell>
              {props.story.books 
                && props.story.books.length 
                && props.story.books.map(book=>(
                  <>
                    {book}
                  </>
              ))}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              利用した予備校・予備校教材
              </b>
            </TableCell>
            <TableCell>
              {props.story.schools
                && props.story.schools.length
                && props.story.schools.map(school => (
                  <>
                    {school}
                  </>
                ))
              }
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              受験した動機
              </b>
            </TableCell>
            <TableCell>
              {props.story.mot}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              具体的な学習方法
              </b>
            </TableCell>
            <TableCell>
              {props.story.studyMethod}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              学習方法の振り返り
              </b>
            </TableCell>
            <TableCell>
              {props.story.regStudy}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              今後の目標
              </b>
            </TableCell>
            <TableCell>
              {props.story.goal}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              BetMeチャレンジを利用した感想
              </b>
            </TableCell>
            <TableCell>
              {props.story.impBetme}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <b>
              現在の年収
              </b>
            </TableCell>
            <TableCell>
              {props.story.income}
            </TableCell>
          </TableRow>

        </TableBody>
      </Table>
    </>
  )
}

export default AuthorStory;